In [34]:
%pylab inline
import pandas as pd
import numpy as np
import pickle

from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score

from math import ceil, sqrt

from collections import defaultdict

Populating the interactive namespace from numpy and matplotlib


C:\Users\Inventario-LSE\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['ceil', 'sqrt', 'clf', 'cm']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [5]:
def piramid(alpha=2, n_in=7, n_out=1):
    neurons = ceil(alpha * sqrt(n_in * n_out))
    ret = [(neurons,)]
    ret += [(neurons-n, n) for n in range(1, neurons)]
    return ret

In [6]:
df_train = pd.read_csv('train_data.csv')
df_test = pd.read_csv('test_data.csv')

In [7]:
X_train = df_train.iloc[:, :-1]
y_train = df_train.iloc[:, -1]
X_test = df_test.iloc[:, :-1]
y_test = df_test.iloc[:, -1]

In [8]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [9]:
params = {
    'activation': ['logistic', 'relu', 'tanh'], 
    'max_iter': [600, 800, 1000],
    'learning_rate_init': [0.001, 0.003, 0.01, 0.0005],
    'hidden_layer_sizes': list(piramid(alpha=0.5, n_in=9) + piramid(alpha=2, n_in=9) + piramid(alpha=3, n_in=9))
}

In [10]:
models = []
for a in params['activation']:
    for m in params['max_iter']:
        for l in params['learning_rate_init']:
            for h in params['hidden_layer_sizes']:
                models.append(['lbfgs', a, m, l, h])
models

[['lbfgs', 'logistic', 600, 0.001, (2,)],
 ['lbfgs', 'logistic', 600, 0.001, (1, 1)],
 ['lbfgs', 'logistic', 600, 0.001, (6,)],
 ['lbfgs', 'logistic', 600, 0.001, (5, 1)],
 ['lbfgs', 'logistic', 600, 0.001, (4, 2)],
 ['lbfgs', 'logistic', 600, 0.001, (3, 3)],
 ['lbfgs', 'logistic', 600, 0.001, (2, 4)],
 ['lbfgs', 'logistic', 600, 0.001, (1, 5)],
 ['lbfgs', 'logistic', 600, 0.001, (9,)],
 ['lbfgs', 'logistic', 600, 0.001, (8, 1)],
 ['lbfgs', 'logistic', 600, 0.001, (7, 2)],
 ['lbfgs', 'logistic', 600, 0.001, (6, 3)],
 ['lbfgs', 'logistic', 600, 0.001, (5, 4)],
 ['lbfgs', 'logistic', 600, 0.001, (4, 5)],
 ['lbfgs', 'logistic', 600, 0.001, (3, 6)],
 ['lbfgs', 'logistic', 600, 0.001, (2, 7)],
 ['lbfgs', 'logistic', 600, 0.001, (1, 8)],
 ['lbfgs', 'logistic', 600, 0.003, (2,)],
 ['lbfgs', 'logistic', 600, 0.003, (1, 1)],
 ['lbfgs', 'logistic', 600, 0.003, (6,)],
 ['lbfgs', 'logistic', 600, 0.003, (5, 1)],
 ['lbfgs', 'logistic', 600, 0.003, (4, 2)],
 ['lbfgs', 'logistic', 600, 0.003, (3, 3)]

In [27]:
results = defaultdict()
results['models'] = []
results['y_preds'] = []
results['cms'] = []
results['accuracies'] = []
results['f1_scores'] = []

In [29]:
for i, (s, a, m, l, h) in zip(range(len(models)),models):
    clf = MLPClassifier(solver = s, activation=a, hidden_layer_sizes=h, learning_rate_init=l, max_iter=m)
    clf.fit(X_train, y_train)
    
    results['models'].append([s, a, h, l, m])
    
    y_pred = clf.predict(X_test)
    results['y_preds'].append(y_pred)
    
    cm = confusion_matrix(y_pred=y_pred, y_true= y_test)
    results['cms'].append(cm.flatten())
    
    print("Modelo {}".format(i))
    print('Acurácia: {}%'.format(round(cm.diagonal().sum() / cm.sum() * 100, 2)))
    print('F-Score: {}%\n'.format(round(f1_score(y_pred=y_pred, y_true=y_test) * 100, 2)))
    
    results['accuracies'].append(round(cm.diagonal().sum() / cm.sum() * 100, 2))
    results['f1_scores'].append(round(f1_score(y_pred=y_pred, y_true=y_test) * 100, 2))

Modelo 0
Acurácia: 87.5%
F-Score: 85.71%

Modelo 1
Acurácia: 83.33%
F-Score: 75.0%

Modelo 2
Acurácia: 79.17%
F-Score: 76.19%

Modelo 3
Acurácia: 83.33%
F-Score: 80.0%

Modelo 4
Acurácia: 83.33%
F-Score: 80.0%

Modelo 5
Acurácia: 70.83%
F-Score: 69.57%

Modelo 6
Acurácia: 83.33%
F-Score: 81.82%

Modelo 7
Acurácia: 83.33%
F-Score: 81.82%

Modelo 8
Acurácia: 75.0%
F-Score: 70.0%

Modelo 9
Acurácia: 66.67%
F-Score: 60.0%

Modelo 10
Acurácia: 75.0%
F-Score: 72.73%

Modelo 11
Acurácia: 75.0%
F-Score: 66.67%

Modelo 12
Acurácia: 70.83%
F-Score: 66.67%

Modelo 13
Acurácia: 79.17%
F-Score: 78.26%

Modelo 14
Acurácia: 62.5%
F-Score: 60.87%

Modelo 15
Acurácia: 79.17%
F-Score: 70.59%

Modelo 16
Acurácia: 62.5%
F-Score: 0.0%

Modelo 17
Acurácia: 75.0%
F-Score: 75.0%

Modelo 18
Acurácia: 83.33%
F-Score: 75.0%



C:\Users\Inventario-LSE\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


Modelo 19
Acurácia: 75.0%
F-Score: 70.0%

Modelo 20
Acurácia: 91.67%
F-Score: 87.5%

Modelo 21
Acurácia: 83.33%
F-Score: 77.78%

Modelo 22
Acurácia: 83.33%
F-Score: 81.82%

Modelo 23
Acurácia: 75.0%
F-Score: 75.0%

Modelo 24
Acurácia: 79.17%
F-Score: 78.26%

Modelo 25
Acurácia: 75.0%
F-Score: 72.73%

Modelo 26
Acurácia: 83.33%
F-Score: 80.0%

Modelo 27
Acurácia: 70.83%
F-Score: 63.16%

Modelo 28
Acurácia: 70.83%
F-Score: 36.36%

Modelo 29
Acurácia: 70.83%
F-Score: 69.57%

Modelo 30
Acurácia: 83.33%
F-Score: 77.78%

Modelo 31
Acurácia: 79.17%
F-Score: 70.59%

Modelo 32
Acurácia: 75.0%
F-Score: 72.73%

Modelo 33
Acurácia: 83.33%
F-Score: 75.0%

Modelo 34
Acurácia: 70.83%
F-Score: 66.67%

Modelo 35
Acurácia: 62.5%
F-Score: 0.0%

Modelo 36
Acurácia: 79.17%
F-Score: 73.68%

Modelo 37
Acurácia: 62.5%
F-Score: 0.0%

Modelo 38
Acurácia: 79.17%
F-Score: 70.59%

Modelo 39
Acurácia: 75.0%
F-Score: 75.0%

Modelo 40
Acurácia: 79.17%
F-Score: 70.59%

Modelo 41
Acurácia: 83.33%
F-Score: 81.82%

Model

Modelo 210
Acurácia: 70.83%
F-Score: 72.0%

Modelo 211
Acurácia: 83.33%
F-Score: 80.0%

Modelo 212
Acurácia: 70.83%
F-Score: 69.57%

Modelo 213
Acurácia: 87.5%
F-Score: 85.71%

Modelo 214
Acurácia: 79.17%
F-Score: 70.59%

Modelo 215
Acurácia: 62.5%
F-Score: 0.0%

Modelo 216
Acurácia: 83.33%
F-Score: 75.0%

Modelo 217
Acurácia: 79.17%
F-Score: 78.26%

Modelo 218
Acurácia: 87.5%
F-Score: 84.21%

Modelo 219
Acurácia: 70.83%
F-Score: 36.36%

Modelo 220
Acurácia: 95.83%
F-Score: 94.74%

Modelo 221
Acurácia: 79.17%
F-Score: 78.26%

Modelo 222
Acurácia: 62.5%
F-Score: 0.0%

Modelo 223
Acurácia: 79.17%
F-Score: 78.26%

Modelo 224
Acurácia: 62.5%
F-Score: 0.0%

Modelo 225
Acurácia: 91.67%
F-Score: 90.0%

Modelo 226
Acurácia: 79.17%
F-Score: 78.26%

Modelo 227
Acurácia: 79.17%
F-Score: 78.26%

Modelo 228
Acurácia: 91.67%
F-Score: 90.0%

Modelo 229
Acurácia: 79.17%
F-Score: 73.68%

Modelo 230
Acurácia: 79.17%
F-Score: 76.19%

Modelo 231
Acurácia: 62.5%
F-Score: 0.0%

Modelo 232
Acurácia: 83.33%
F

Modelo 398
Acurácia: 79.17%
F-Score: 78.26%

Modelo 399
Acurácia: 79.17%
F-Score: 76.19%

Modelo 400
Acurácia: 75.0%
F-Score: 70.0%

Modelo 401
Acurácia: 62.5%
F-Score: 0.0%

Modelo 402
Acurácia: 87.5%
F-Score: 80.0%

Modelo 403
Acurácia: 83.33%
F-Score: 80.0%

Modelo 404
Acurácia: 70.83%
F-Score: 69.57%

Modelo 405
Acurácia: 79.17%
F-Score: 73.68%

Modelo 406
Acurácia: 91.67%
F-Score: 90.0%

Modelo 407
Acurácia: 70.83%
F-Score: 46.15%

Modelo 408
Acurácia: 66.67%
F-Score: 69.23%

Modelo 409
Acurácia: 62.5%
F-Score: 0.0%

Modelo 410
Acurácia: 75.0%
F-Score: 66.67%

Modelo 411
Acurácia: 79.17%
F-Score: 73.68%

Modelo 412
Acurácia: 75.0%
F-Score: 70.0%

Modelo 413
Acurácia: 70.83%
F-Score: 69.57%

Modelo 414
Acurácia: 75.0%
F-Score: 72.73%

Modelo 415
Acurácia: 83.33%
F-Score: 81.82%

Modelo 416
Acurácia: 75.0%
F-Score: 70.0%

Modelo 417
Acurácia: 79.17%
F-Score: 76.19%

Modelo 418
Acurácia: 75.0%
F-Score: 72.73%

Modelo 419
Acurácia: 75.0%
F-Score: 70.0%

Modelo 420
Acurácia: 75.0%
F-Sc

Modelo 583
Acurácia: 58.33%
F-Score: 44.44%

Modelo 584
Acurácia: 79.17%
F-Score: 70.59%

Modelo 585
Acurácia: 70.83%
F-Score: 72.0%

Modelo 586
Acurácia: 91.67%
F-Score: 88.89%

Modelo 587
Acurácia: 75.0%
F-Score: 66.67%

Modelo 588
Acurácia: 75.0%
F-Score: 70.0%

Modelo 589
Acurácia: 70.83%
F-Score: 66.67%

Modelo 590
Acurácia: 75.0%
F-Score: 66.67%

Modelo 591
Acurácia: 79.17%
F-Score: 70.59%

Modelo 592
Acurácia: 83.33%
F-Score: 80.0%

Modelo 593
Acurácia: 91.67%
F-Score: 88.89%

Modelo 594
Acurácia: 70.83%
F-Score: 72.0%

Modelo 595
Acurácia: 70.83%
F-Score: 72.0%

Modelo 596
Acurácia: 75.0%
F-Score: 75.0%

Modelo 597
Acurácia: 87.5%
F-Score: 82.35%

Modelo 598
Acurácia: 79.17%
F-Score: 76.19%

Modelo 599
Acurácia: 79.17%
F-Score: 76.19%

Modelo 600
Acurácia: 91.67%
F-Score: 88.89%

Modelo 601
Acurácia: 66.67%
F-Score: 69.23%

Modelo 602
Acurácia: 79.17%
F-Score: 66.67%

Modelo 603
Acurácia: 66.67%
F-Score: 50.0%

Modelo 604
Acurácia: 75.0%
F-Score: 70.0%

Modelo 605
Acurácia: 87.

In [36]:
best_results_index = [i for i in range(len(results['accuracies'])) if results['accuracies'][i] > 90 and 
                                                                      results['f1_scores'][i] > 90]

In [37]:
best_models = defaultdict()
best_models['models'] = []
best_models['y_preds'] = []
best_models['cms'] = []
best_models['accuracies'] = []
best_models['f1_scores'] = []

In [38]:
for i in best_results_index:
    best_models['models'].append(results['models'][i])
    best_models['y_preds'].append(results['y_preds'][i])
    best_models['cms'].append(results['cms'][i])
    best_models['accuracies'].append(results['accuracies'][i])
    best_models['f1_scores'].append(results['f1_scores'][i])

In [39]:
best_models

defaultdict(None,
            {'models': [['lbfgs', 'logistic', (2,), 0.0005, 600],
              ['lbfgs', 'logistic', (2,), 0.003, 800],
              ['lbfgs', 'logistic', (3, 3), 0.0005, 1000],
              ['lbfgs', 'relu', (1, 8), 0.001, 600],
              ['lbfgs', 'relu', (2,), 0.0005, 800],
              ['lbfgs', 'tanh', (5, 1), 0.001, 1000]],
             'y_preds': [array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1,
                     1, 2], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1,
                     1, 2], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                     1, 1], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                     1, 1], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                     1, 1], 

In [40]:
arq = open('best_models.txt', 'wb')
pickle.dump(best_models, arq)
arq.close()