In [1]:
import pandas as pd
import numpy as np
import pickle

from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

from collections import defaultdict

In [2]:
df_train = pd.read_csv('train_data.csv')
df_test = pd.read_csv('test_data.csv')

In [13]:
df_test = 

index  Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0      11   29  23.010000       82    5.663  1.145436  35.5900    26.720000   
1      77   43  31.250000      103    4.328  1.099601  25.7816    12.718960   
2      96   44  27.887617       99    9.208  2.248594  12.6757     5.478170   
3      53   45  20.829995       74    4.560  0.832352   7.7529     8.237405   
4      68   46  20.830000       88    3.420  0.742368  12.8700    18.550000   
5      86   48  28.125000       90    2.540  0.563880  15.5325    10.222310   
6      54   49  20.956608       94   12.305  2.853119  11.2406     8.412175   
7      93   49  32.461911      134   24.887  8.225983  42.3914    10.793940   
8      63   51  22.892820      103    2.740  0.696143   8.0163     9.349775   
9      31   53  36.790166      101   10.175  2.534932  27.1841    20.030000   
10    104   57  34.838148       95   12.548  2.940415  33.1612     2.364950   
11     89   58  29.154519      139   16.582  5.685415  22.8884    10.262660   
12     17   61  32.038959       85   18.077  3.790144  30.7729     7.780255   
13     59   62  22.656250       92    3.482  0.790182   9.8648    11.236235   
14     59   62  22.656250       92    3.482  0.790182   9.8648    11.236235   
15     18   64  34.529723       95    4.427  1.037394  21.2117     5.462620   
16     30   66  36.212279      101   15.533  3.869788  74.7069     7.539550   
17     57   68  21.082813      102    6.200  1.559920   9.6994     8.574655   
18     73   72  23.620000      105    4.420  1.144780  21.7800    17.860000   
19      8   73  22.000000       97    3.350  0.801543   4.4700    10.358725   
20     46   75  25.700000       94    8.079  1.873251  65.9260     3.741220   
21      9   75  23.000000       83    4.952  1.013839  17.1270    11.578990   
22    115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

    Resistin     MCP.1  Classification     id  
0    4.58000   174.800               1   78.0  
1   38.65310   775.322               2   48.0  
2   23.03306   407.206               2  113.0  
3   28.03230   382.955               2   59.0  
4   13.56000   301.210               2   53.0  
5   16.11032  1698.440               2   31.0  
6   23.11770   573.630               2   89.0  
7    5.76800   656.393               2   11.0  
8   11.55492   359.232               2   14.0  
9   10.26309   695.754               1   84.0  
10   9.95420   655.834               2   63.0  
11  13.97399   923.886               2   71.0  
12  13.68392   444.395               1   58.0  
13  10.69548   703.973               2  100.0  
14  10.69548   703.973               2   76.0  
15   6.70188   252.449               1   85.0  
16  22.32024   864.968               1   56.0  
17  13.74244   448.799               2   21.0  
18   4.82000   195.940               2   60.0  
19   6.28445   136.855               1   86.0  
20   4.49685   206.802               1   77.0  
21   7.09130   318.302               1  112.0  
22   4.35000    90.090               2   36.0

In [12]:
X_train = df_train.iloc[:, :-1]
y_train = df_train.iloc[:, -1]
X_test = df_test.iloc[:, :-1].drop('index', axis=1)
y_test = df_test.iloc[:, -1].drop('index', axis=1)

ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>

In [4]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [5]:
best_models = defaultdict()
arq = open('best_models.txt', 'rb')
best_models = pickle.load(arq)
arq.close()

In [6]:
best_models

defaultdict(None,
            {'models': [['lbfgs', 'logistic', (2,), 0.0005, 600],
              ['lbfgs', 'logistic', (2,), 0.003, 800],
              ['lbfgs', 'logistic', (3, 3), 0.0005, 1000],
              ['lbfgs', 'relu', (1, 8), 0.001, 600],
              ['lbfgs', 'relu', (2,), 0.0005, 800],
              ['lbfgs', 'tanh', (5, 1), 0.001, 1000]],
             'y_preds': [array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1,
                     1, 2], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1,
                     1, 2], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                     1, 1], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                     1, 1], dtype=int64),
              array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                     1, 1], 

In [7]:
models = []
for s, a, h, l, e in best_models['models']:
    models.append(MLPClassifier(solver=s, activation=a, hidden_layer_sizes=h, learning_rate_init=l, max_iter=e))

In [8]:
acc = 0
while(acc < 0.95):
    for model in models:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_pred=y_pred, y_true=y_test)
        print(acc)

ValueError: Unknown label type: (array([ 417.114,  468.786,  554.697,  928.22 ,  773.92 ,  530.41 ,
        280.694,  354.6  ,  313.73 ,  632.22 ,  165.02 ,   63.61 ,
        191.72 ,  588.46 ,  534.224,  572.783,  904.981,  733.797,
       1227.91 ,  586.173,  887.16 , 1102.11 ,  667.928,  581.313,
        358.624,  960.246,  473.859,  585.307,  634.602,  263.499,
        378.996,  618.272,  698.789,  377.227,  335.393,  270.142,
        200.976,  225.88 ,  209.749,  215.769,  232.006,   45.843,
        488.829,  552.444,  481.949,  321.919,   90.6  ,  199.055,
        713.239,  737.672,  355.31 ,  518.586,  635.049,  395.976,
        220.66 ,  193.87 ,  244.75 ,  513.66 ,  312.   ,  806.724,
        483.377,  783.796,  910.489,  426.175,  738.034,  799.898,
       1041.843, 1698.44 , 1078.359, 1698.44 ,  638.261,  994.316,
        764.667,  396.021,  602.486,  293.123,  256.001,  353.568,
        572.401,  269.487,  396.648,  232.018,  788.902,  621.273,
        209.19 ,  198.4  ,   99.45 ,  218.28 ,  268.23 ,  330.16 ,
        314.05 ,  392.46 ]),)

In [57]:
y_pred

array([2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1,
       1, 2], dtype=int64)

In [69]:
pd.concat([df_test.id, pd.Series(y_pred)], axis=1, keys=['id', 'Classification']).to_csv('output.csv', index=False)